/**
 * Canonical structured workout shape for the assistant UI.
 *
 * Flow: generation (`assistantSingleSessionGeneration` / programme LLM days) produces a `BuiltWorkout`,
 * then `builtWorkoutToStructuredWorkout` maps it here. The client renders this object only — it does not
 * invent exercises or prescriptions.
 */

import { formatIntRange } from "@/lib/formatPrescriptionDisplay";
import type { BuiltWorkout } from "@/lib/workoutBuilder";

/** Single exercise row shown on the assistant workout card. */
export type AssistantStructuredWorkoutExercise = {
  slotLabel: string;
  exerciseName: string;
  /** Legacy mirror fields — keep in sync for older UI. */
  slot: string;
  exercise: string;
  sets: string;
  reps: string;
  rir: string;
  rest: string;
  rationale: string;
};

/** How often per week the session should be performed and recovery context. */
export type AssistantWorkoutFrequency = {
  timesPerWeek: number;
  restDaysBetween: number;
  rationale: string;
};

/** v1 contract — matches `AssistantResponse.structuredWorkout` on the API. */
export type AssistantStructuredWorkoutV1 = {
  sessionTitle: string;
  sessionGoal: string;
  purposeSummary: string;
  exercises: AssistantStructuredWorkoutExercise[];
  notes?: string;
  note: string;
  /** Recommended frequency and rest-day guidance for this session. */
  weeklyFrequency?: AssistantWorkoutFrequency;
  /** Which server path produced this card (mechanical proof). */
  debugGenerator?: string;
  /** Short stack / function chain for audits. */
  debugTrace?: string;
};

export type BuiltWorkoutToStructuredMeta = {
  debugGenerator: string;
  debugTrace?: string;
};

export function builtWorkoutToStructuredWorkout(
  workout: BuiltWorkout,
  meta?: BuiltWorkoutToStructuredMeta
): AssistantStructuredWorkoutV1 {
  const sessionTitle = `${workout.sessionType.replace("_", " ")} workout`;
  const sessionGoal = workout.purposeSummary;
  const baseNote =
    workout.notes[0] ??
    workout.warnings[0] ??
    "Run compounds first, then accessories, and keep execution quality high.";
  const debugLine = meta
    ? `DEBUG: generated by ${meta.debugGenerator}${meta.debugTrace ? ` | ${meta.debugTrace}` : ""}`
    : "";
  const note = debugLine ? `${debugLine}\n\n${baseNote}` : baseNote;
  return {
    sessionTitle,
    sessionGoal,
    purposeSummary: workout.purposeSummary,
    exercises: workout.exercises.map((ex) => ({
      slotLabel: ex.slotLabel,
      exerciseName: ex.exerciseName,
      slot: ex.slotLabel,
      exercise: ex.exerciseName,
      sets: formatIntRange(ex.sets),
      reps: formatIntRange(ex.repRange),
      rir: formatIntRange(ex.rirRange),
      rest: `${formatIntRange(ex.restSeconds)}s`,
      rationale: ex.rationale,
    })),
    notes: note,
    note,
    ...(workout.weeklyFrequency
      ? { weeklyFrequency: workout.weeklyFrequency }
      : {}),
    ...(meta
      ? {
          debugGenerator: meta.debugGenerator,
          ...(meta.debugTrace ? { debugTrace: meta.debugTrace } : {}),
        }
      : {}),
  };
}
